buildscript {
    dependencies {
        classpath group: 'org.hsqldb',
                  name: 'hsqldb',
                  version: '2.7.1'
    }
}

plugins {
    id 'java'
    id "org.flywaydb.flyway" version "9.7.0"
}

sourceCompatibility = 17

repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/milestone/" }
}

def springVersion = '6.0.0-RC1'
def flywayVersion = '9.7.0'
def lombokVersion = '1.18.24'
def hibernateVersion = '6.1.5.Final'
def log4jVersion = '2.19.0'

dependencies {

    implementation group: 'org.hsqldb',
            name: 'hsqldb',
            version: '2.7.1'

    implementation group: 'org.springframework',
            name: 'spring-context',
            version: springVersion

    implementation group: 'org.springframework',
            name: 'spring-jdbc',
            version: springVersion

    compileOnly group: 'org.flywaydb',
            name: 'flyway-core',
            version: flywayVersion

    compileOnly group: 'org.projectlombok',
            name: 'lombok',
            version: lombokVersion

    annotationProcessor group: 'org.projectlombok',
            name: 'lombok',
            version: lombokVersion

    // for hibernate @Audit demo only

    implementation group: 'org.hibernate',
            name: 'hibernate-core',
            version: hibernateVersion

    implementation group: 'org.hibernate',
            name: 'hibernate-envers',
            version: hibernateVersion

    implementation group: 'org.springframework',
            name: 'spring-orm',
            version: springVersion

    implementation group: 'org.apache.logging.log4j',
            name: 'log4j-api',
            version: log4jVersion

    implementation group: 'org.apache.logging.log4j',
            name: 'log4j-core',
            version: log4jVersion


}

flyway {
    def props = new Properties()

    file("src/main/resources/application.properties")
            .withInputStream { props.load(it) }

    url = props.getProperty("db.url")
    user = props.getProperty("db.user")
    password = props.getProperty("db.pass")

    locations = ['classpath:flyway']
}
