buildscript {
    dependencies {
        classpath group: 'org.hsqldb',
                  name: 'hsqldb',
                  version: '2.6.1'
    }
}

plugins {
    id 'java'
    id "org.flywaydb.flyway" version "8.0.2"
}

sourceCompatibility = 17

repositories {
    mavenCentral()
}

def springVersion = '5.3.12'
def flywayVersion = '8.0.2'
def lombokVersion = '1.18.22'

dependencies {

    implementation group: 'org.hsqldb',
            name: 'hsqldb',
            version: '2.6.1'

    implementation group: 'org.springframework',
            name: 'spring-context',
            version: springVersion

    implementation group: 'org.springframework',
            name: 'spring-jdbc',
            version: springVersion

    compileOnly group: 'org.flywaydb',
            name: 'flyway-core',
            version: flywayVersion

    compileOnly group: 'org.projectlombok',
            name: 'lombok',
            version: lombokVersion

    annotationProcessor group: 'org.projectlombok',
            name: 'lombok',
            version: lombokVersion

}

// ./gradlew clean build flywayInfo
// ./gradlew clean build flywayMigrate -i

flyway {
    def props = new Properties()

    file("src/main/resources/application.properties")
            .withInputStream { props.load(it) }

    url = props.getProperty("db.url")
    user = props.getProperty("db.user")
    password = props.getProperty("db.pass")

    locations = ['classpath:flyway']
}
